[package]
name = "aimer_reload_protocol-fuzz"
version = "0.0.0"
publish = false
edition = "2024"
autobins = false

[package.metadata]
cargo-fuzz = true

[dependencies]
aimer_reload_protocol = { path = ".." }
libfuzzer-sys = "0.4"

[[bin]]
name = "unauthenticated_connection"
path = "fuzz_targets/unauthenticated_connection.rs"
test = false
doc = false
bench = false

[[bin]]
name = "authenticated_connection"
path = "fuzz_targets/authenticated_connection.rs"
test = false
doc = false
bench = false

[[bin]]
name = "terminal_result"
path = "fuzz_targets/terminal_result.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]