[package]
name = "aimer_scroll"
version = "0.1.0"
edition = "2024"

[features]
portable-guest = ["aimer_widget/portable-guest"]

[dependencies]
aimer_animation.workspace = true
aimer_attribute.workspace = true
aimer_events.workspace = true
aimer_macro.workspace = true
aimer_utils.workspace = true
aimer_widget.workspace = true
hashbrown.workspace = true



[dev-dependencies]
aimer_canvas.workspace = true
aimer_container.workspace = true
aimer_flex.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
