[package]
name = "aimer_animation"
version = "0.1.0"
edition = "2024"

[features]
portable-guest = ["aimer_widget/portable-guest"]

[dependencies]
aimer_macro.workspace = true
aimer_widget.workspace = true
aimer_attribute.workspace = true
aimer_events.workspace = true
aimer_canvas.workspace = true
aimer_utils.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
