import UIKit

// Rust entrypoint generated by `#[aimer_main]`.
@_silgen_name("__generated_entrance_point")
func __generated_entrance_point()

// Software keyboard forwarding into Rust.
@_silgen_name("trigger_rust_backspace")
func trigger_rust_backspace()

@_silgen_name("trigger_rust_insert_text")
func trigger_rust_insert_text(_ ptr: UnsafePointer<UInt8>, _ len: Int)

@_cdecl("aimer_ios_show_keyboard")
func aimer_ios_show_keyboard() {
    DispatchQueue.main.async {
        KeyboardForwarder.shared.showKeyboard()
    }
}

@_cdecl("aimer_ios_dismiss_keyboard")
func aimer_ios_dismiss_keyboard() {
    DispatchQueue.main.async {
        KeyboardForwarder.shared.dismissKeyboard()
    }
}

// Frame scheduling into Rust.
// A CADisplayLink drives redraws in sync with the display (up to 120 fps on
// ProMotion). It stays paused while idle; Rust unpauses it when a frame is
// requested and pauses it again once no more frames are pending.
@_silgen_name("aimer_ios_frame_tick")
func aimer_ios_frame_tick()

final class FrameDriver {
    static let shared = FrameDriver()
    private var displayLink: CADisplayLink?

    func start() {
        guard displayLink == nil else { return }
        let link = CADisplayLink(target: self, selector: #selector(tick))
        if #available(iOS 15.0, *) {
            // Allow the system to run up to 120 Hz on ProMotion displays.
            link.preferredFrameRateRange = CAFrameRateRange(minimum: 80, maximum: 120, preferred: 120)
        }
        // Start paused; frames are produced on demand.
        link.isPaused = true
        link.add(to: .main, forMode: .common)
        displayLink = link
    }

    func requestFrame() {
        displayLink?.isPaused = false
    }

    func pause() {
        displayLink?.isPaused = true
    }

    @objc private func tick() {
        aimer_ios_frame_tick()
    }
}

@_cdecl("aimer_ios_request_frame")
func aimer_ios_request_frame() {
    DispatchQueue.main.async {
        FrameDriver.shared.requestFrame()
    }
}

@_cdecl("aimer_ios_pause_frames")
func aimer_ios_pause_frames() {
    DispatchQueue.main.async {
        FrameDriver.shared.pause()
    }
}

final class KeyboardForwardingTextView: UITextView, UITextViewDelegate {
    override var canBecomeFirstResponder: Bool { true }

    // Keep a placeholder so the backspace key stays enabled.
    private let placeholder = " "

    func ensurePlaceholder() {
        if (text ?? "").isEmpty {
            text = placeholder
            selectedRange = NSRange(location: placeholder.utf16.count, length: 0)
        }
    }

    override func didMoveToWindow() {
        super.didMoveToWindow()
        // NOTE: `isHidden = true` disables first-responder interaction and prevents
        // software keyboard callbacks. Keep the view effectively invisible via
        // `alpha`/size instead.
        delegate = self
        isHidden = false
        isScrollEnabled = false
        autocorrectionType = .no
        spellCheckingType = .no
        smartQuotesType = .no
        smartDashesType = .no
        smartInsertDeleteType = .no
        keyboardDismissMode = .none
        ensurePlaceholder()
    }

    private func forward(_ text: String) {
        if let data = text.data(using: .utf8) {
            data.withUnsafeBytes { rawBuf in
                if let base = rawBuf.bindMemory(to: UInt8.self).baseAddress {
                    trigger_rust_insert_text(base, rawBuf.count)
                }
            }
        }
    }

    // `shouldChangeTextIn` is intentionally NOT called by UIKit while a multistage
    // input method is composing "marked text" (Chinese Pinyin, Japanese Kana,
    // Korean Hangul, ...); it fires only once the text is finalized/committed.
    // That makes it the reliable hook for capturing composed CJK input, which the
    // previous `insertText` override missed because committed marked text does not
    // always route through `insertText(_:)`.
    func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {
        if text.isEmpty {
            // A deletion (backspace).
            trigger_rust_backspace()
        } else {
            forward(text)
        }
        return true
    }

    func textViewDidChange(_ textView: UITextView) {
        // Never reset while an IME composition is still in progress, otherwise the
        // candidate window is dismissed mid-composition.
        if textView.markedTextRange != nil { return }
        // Collapse the hidden buffer back to the placeholder so it never grows and
        // the backspace key always has something to delete.
        textView.text = placeholder
        textView.selectedRange = NSRange(location: placeholder.utf16.count, length: 0)
    }
}

final class KeyboardForwarder {
    static let shared = KeyboardForwarder()
    private(set) var inputView: KeyboardForwardingTextView?
    private var installAttempts: Int = 0
    private var installScheduled: Bool = false
    private var observers: [NSObjectProtocol] = []

    func dismissKeyboard() {
        guard let v = inputView else { return }
        v.resignFirstResponder()
    }

    func showKeyboard() {
        ensureFirstResponder()
    }

    private func ensureFirstResponder() {
        if inputView == nil {
            installIfPossible()
            return
        }
        guard let v = inputView else { return }
        v.ensurePlaceholder()
        _ = v.becomeFirstResponder()
    }

    private func keyWindow() -> UIWindow? {
        if #available(iOS 13.0, *) {
            let scenes = UIApplication.shared.connectedScenes
                .compactMap { $0 as? UIWindowScene }

            // Prefer a foreground-active scene.
            let orderedScenes = scenes.sorted { lhs, rhs in
                let lhsActive = lhs.activationState == .foregroundActive
                let rhsActive = rhs.activationState == .foregroundActive
                return lhsActive && !rhsActive
            }

            for scene in orderedScenes {
                if let win = scene.windows.first(where: { $0.isKeyWindow }) {
                    return win
                }
            }
        }

        // Fallback for older iOS / edge cases.
        return UIApplication.shared.windows.first(where: { $0.isKeyWindow })
    }

    private func scheduleRetry() {
        guard !installScheduled else { return }
        installScheduled = true

        // Retry a few times to wait for winit to create its UIWindow.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.10) { [weak self] in
            guard let self else { return }
            self.installScheduled = false
            self.installIfPossible()
        }
    }

    func installIfPossible() {
        guard inputView == nil else { return }

        guard let window = keyWindow() else {
            installAttempts += 1
            if installAttempts < 50 {
                scheduleRetry()
            }
            return
        }

        let v = KeyboardForwardingTextView(frame: CGRect(x: 0, y: 0, width: 1, height: 1))
        v.alpha = 0.01
        window.addSubview(v)
        window.bringSubviewToFront(v)
        v.ensurePlaceholder()
        inputView = v

    }

    func start() {
        // Important: winit calls `UIApplicationMain` internally.
        // Depending on iOS / scene lifecycle, a custom `UIApplicationDelegate` may not be
        // reliably used. So we install from notifications + retry loop instead of relying on
        // delegate callbacks.
        if observers.isEmpty {
            let center = NotificationCenter.default

            observers.append(center.addObserver(
                forName: UIApplication.didBecomeActiveNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in
                self?.installIfPossible()
            })

            observers.append(center.addObserver(
                forName: UIApplication.willEnterForegroundNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in
                self?.installIfPossible()
            })

            // When the software keyboard is shown, UIKit/winit may change first responder.
            // Re-assert first responder so `insertText`/`deleteBackward` keep coming to our view.
            observers.append(center.addObserver(
                forName: UIResponder.keyboardWillShowNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in
                self?.ensureFirstResponder()
            })

            observers.append(center.addObserver(
                forName: UIResponder.keyboardDidShowNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in

                self?.ensureFirstResponder()
            })

            observers.append(center.addObserver(
                forName: UIWindow.didBecomeKeyNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in
                self?.ensureFirstResponder()
            })
        }

        // Also try immediately (this will schedule retries until a key window exists).
        installIfPossible()
    }
}

KeyboardForwarder.shared.start()
FrameDriver.shared.start()

#if DEBUG
print("Starting AimerApplication...")
#endif
__generated_entrance_point()