use std::fmt;
use std::hash::{Hash, Hasher};
use std::panic::Location;
use std::sync::atomic::{AtomicU64, Ordering};

use aimer_utils::PanicSite;

/// A stable identity token attached to a [`Widget`](crate::Widget) so the
/// reconciliation algorithm can match old elements to new ones across rebuilds.
///
/// # Constructors
///
/// - [`Key::Value`] equality-based. Two widgets with the same value are
///   considered "the same element". This is the most common key type and covers
///   list-item IDs, tab names, route paths, etc.
/// - [`Key::Object`] identity-based. Matched by pointer/identity, not by
///   value. Use [`Key::unique()`] to generate a key that never matches anything
///   else (useful for forcing a full state reset).
/// - [`Key::Static`] keyed by a static string, which is useful for a key
///   generated by the [`key!`](aimer_macro::key) macro.
///
/// Every constructor records its caller in `create_at`. The location is
/// included in [`Debug`] output to make a reconciliation failure point back to
/// the key's creation site, but it never participates in key equality or
/// hashing.
///
/// # Example
///
/// ```rust,ignore
/// use aimer::Key;
///
/// Column::create_new(vec![
///     MyItem::create_new(Some(Key::Value("item-1".into())), ...),
///     MyItem::create_new(Some(Key::Value("item-2".into())), ...),
/// ])
/// ```
#[derive(Clone)]
pub struct Key {
    inner: KeyInner,
    create_at: &'static Location<'static>,
}

impl Key {
    #[inline]
    pub fn with_location(self, location: &'static Location<'static>) -> Self {
        Self {
            inner: self.inner,
            create_at: location,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum KeyInner {
    /// Equality-based key. Two widgets with the same `Value` are "the same".
    Value(String),
    /// Identity-based key. Matched by `ptr::eq` semantics — two `Object` keys
    /// are equal only if they originate from the same [`Key::unique()`] call.
    Object(usize),

    /// Compile-time-based key. Matched by pointer/identity, not by value. use
    /// the `key!` macro to generate a key that can keep the state across
    /// the builds
    Static(&'static str),
}

impl fmt::Debug for Key {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("Key")
            .field("inner", &self.inner)
            .field("create_at", &self.create_at)
            .finish()
    }
}

impl PartialEq for Key {
    fn eq(&self, other: &Self) -> bool {
        self.inner == other.inner
    }
}

impl Eq for Key {}

impl Hash for Key {
    #[inline]
    fn hash<H: Hasher>(&self, state: &mut H) {
        match &self.inner {
            KeyInner::Value(s) => {
                state.write_u8(0);
                state.write(s.as_bytes());
            }
            KeyInner::Object(id) => {
                state.write_u8(1);
                state.write_usize(*id);
            }
            KeyInner::Static(s) => {
                state.write_u8(2);
                state.write(s.as_bytes());
            }
        }
    }
}
/// Ergonomic conversions so callers can pass a bare string literal or `String`
/// wherever a `Key` is expected (e.g. `page_storage::read_or("my-tab", 0)`),
/// producing the common equality-based [`Key::Value`].
impl From<&str> for Key {
    #[track_caller]
    fn from(s: &str) -> Self {
        Self::with_inner(KeyInner::Value(s.to_owned()), Location::caller())
    }
}

impl From<String> for Key {
    #[track_caller]
    fn from(s: String) -> Self {
        Self::with_inner(KeyInner::Value(s), Location::caller())
    }
}

static UNIQUE_COUNTER: AtomicU64 = AtomicU64::new(0);

impl Key {
    /// Creates an equality-based key from an owned value.
    #[allow(non_snake_case)]
    #[track_caller]
    pub fn Value(value: String) -> Self {
        Self::with_inner(KeyInner::Value(value), Location::caller())
    }

    /// Creates an identity-based key from a unique identity value.
    #[allow(non_snake_case)]
    #[track_caller]
    pub fn Object(id: usize) -> Self {
        Self::with_inner(KeyInner::Object(id), Location::caller())
    }

    /// Creates a key backed by a compile-time string.
    #[allow(non_snake_case)]
    #[track_caller]
    pub fn Static(value: &'static str) -> Self {
        Self::with_inner(KeyInner::Static(value), Location::caller())
    }

    #[inline]
    fn with_inner(inner: KeyInner, create_at: &'static Location<'static>) -> Self {
        Self { inner, create_at }
    }

    pub(crate) fn diagnostic_description(&self) -> String {
        format!("value {:?}", self.inner)
    }

    pub(crate) fn diagnostic_site(&self) -> PanicSite {
        PanicSite::of(self.create_at)
    }

    /// Generate a globally unique key. Each call returns a key that does not
    /// equal any other key — useful for forcing a state reset on rebuild.
    #[track_caller]
    pub fn unique() -> Self {
        Self::with_inner(
            KeyInner::Object(UNIQUE_COUNTER.fetch_add(1, Ordering::Relaxed) as usize),
            Location::caller(),
        )
    }
}

#[cfg(test)]
mod test {
    use aimer_macro::key;

    use super::*;
    #[test]
    fn test_unique() {
        let key1 = Key::unique();
        let key2 = Key::unique();
        assert_ne!(key1, key2);
    }

    #[test]
    fn test_compile_tile_unique() {
        let key1 = key!();
        let key2 = key!();
        assert_ne!(key1, key2);
    }

    #[test]
    fn debug_includes_creation_location() {
        let key = Key::Value("debug-location".to_owned());
        let debug = format!("{key:?}");

        assert!(debug.contains("create_at"));
        assert!(debug.contains(file!()));
    }

    #[test]
    fn creation_location_is_not_key_identity() {
        let first = Key::Value("same-value".to_owned());
        let second = Key::Value("same-value".to_owned());

        assert_eq!(first, second);

        let mut first_hash = std::collections::hash_map::DefaultHasher::new();
        first.hash(&mut first_hash);
        let mut second_hash = std::collections::hash_map::DefaultHasher::new();
        second.hash(&mut second_hash);
        assert_eq!(first_hash.finish(), second_hash.finish());
    }

    #[test]
    fn key_macro_records_the_call_site() {
        let key = key!();
        let debug = format!("{key:?}");

        assert!(debug.contains(file!()));
    }
}
