[package]
name = "aimer_text"
version = "0.1.0"
edition = "2024"

[features]
default = []
apple-core-text = [
    "aimer_cupid/apple-core-text",
    "aimer_canvas/apple-core-text",
]
portable-guest = [
    "dep:aimer_anteros",
    "aimer_style/portable-guest",
    "aimer_widget/portable-guest",
]

[dependencies]
aimer_anteros = { workspace = true, optional = true }
aimer_accessibility.workspace = true
aimer_canvas.workspace = true
aimer_cupid.workspace = true
aimer_macro.workspace = true
aimer_attribute.workspace = true
aimer_color.workspace = true
aimer_widget.workspace = true
aimer_style.workspace = true
aimer_events.workspace = true
aimer_modal.workspace = true
aimer_ctxmenu.workspace = true
aimer_native.workspace = true
aimer_utils.workspace = true
aimer_std.workspace = true
unicode-linebreak.workspace = true
unicode-segmentation.workspace = true
unicode-bidi.workspace = true

[dev-dependencies]
winit.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures.workspace = true
