use std::error::Error;
use std::fmt::{self, Write};
use std::str::FromStr;

/// Version of the canonical development-host configuration text format.
pub const DEVELOPMENT_HOST_CONFIG_VERSION: u64 = 1;

/// Largest development-host configuration accepted by the parser, in bytes.
///
/// The limit is applied before lines or values are inspected. It keeps private
/// environment variables and app-private session files from becoming an
/// unbounded parsing or allocation input.
pub const MAX_DEVELOPMENT_HOST_CONFIG_TEXT_BYTES: usize = 4_096;

const MAX_FUEL: u64 = 1_000_000_000;
const MAX_MODULE_BYTES: u64 = 256 * 1_024 * 1_024;
const MAX_MEMORY_PAGES: u64 = 65_536;
const MAX_TABLE_ELEMENTS: u64 = 1_000_000;
const MAX_CALL_DEPTH: u64 = 65_536;
const MAX_CHUNK_BYTES: u64 = 16 * 1_024 * 1_024;
const MAX_DIAGNOSTIC_BYTES: u64 = 1_024 * 1_024;
const MAX_TERMINAL_RESULTS: u64 = 1_024;
const MAX_IO_TIMEOUT_MS: u64 = 300_000;
const MAX_CREDENTIAL_TTL_MS: u64 = 86_400_000;
const MAX_AUTHENTICATION_FAILURES: u64 = 1_024;
const MAX_AUTHENTICATION_BACKOFF_MS: u64 = 60_000;
const MAX_MODEL_DOCUMENT_BYTES: u64 = 64 * 1_024 * 1_024;
const MAX_MODEL_ITEMS: u64 = 1_000_000;
const MAX_MODEL_PROPERTIES: u64 = 4_000_000;
const MAX_WIDGET_DEPTH: u64 = 4_096;
const MAX_RETIRED_GENERATIONS: u64 = 1_024;
const MAX_CALLBACK_BINDINGS: u64 = 1_000_000;
const MAX_QUEUE_CAPACITY: u64 = 65_536;

/// Secret-free resource policy used to construct a development reload host.
///
/// This value contains only primitive execution, transport, authentication
/// defense, model, generation, state-transfer, and queue ceilings. It never
/// contains a session identifier or authentication token. Use
/// [`Self::cli_safe_profile`] when the CLI needs the explicit built-in profile;
/// this type deliberately does not implement [`Default`].
///
/// Profiles can be transported as bounded canonical text with [`Self::to_text`]
/// and parsed with [`str::parse`]. Every field is required while parsing, and
/// serialization validates programmatic builder changes before producing text.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DevelopmentHostConfig {
    widget_ir_diagnostics: bool,
    runtime_fuel_per_call: u64,
    max_module_bytes: usize,
    runtime_max_memory_pages: u32,
    runtime_max_table_elements: u32,
    runtime_max_call_depth: u32,
    protocol_max_chunk_bytes: usize,
    protocol_max_diagnostic_bytes: usize,
    protocol_max_terminal_results: usize,
    protocol_io_timeout_ms: u64,
    listener_credential_ttl_ms: u64,
    listener_max_authentication_failures: u32,
    listener_authentication_backoff_ms: u64,
    model_max_document_bytes: usize,
    model_max_state_entries: u32,
    model_max_widget_nodes: u32,
    model_max_properties: u32,
    model_max_widget_depth: u32,
    generation_max_retired: usize,
    max_callback_bindings: u32,
    state_transfer_migration_fuel: u64,
    reload_command_queue_capacity: usize,
    event_queue_capacity: usize,
}

macro_rules! config_accessors {
    ($( $setter:ident => $getter:ident: $ty:ty => $doc:literal, )+) => {
        $(
            #[doc = $doc]
            #[inline]
            pub const fn $setter(mut self, value: $ty) -> Self {
                self.$setter = value;
                self
            }

            #[doc = concat!("Returns the value configured by [`Self::", stringify!($setter), "`].")]
            #[inline]
            pub const fn $getter(self) -> $ty {
                self.$setter
            }
        )+
    };
}

impl DevelopmentHostConfig {
    /// Creates the explicit, conservative profile generated by the Aimer CLI.
    ///
    /// The profile permits a 16 MiB module, uses 64 KiB wire chunks, gives each
    /// guest call and state migration ten million fuel units, and keeps all
    /// listener and application queues small and bounded. Callers should persist
    /// the resulting canonical text alongside, never inside, session secrets.
    #[inline]
    pub const fn cli_safe_profile() -> Self {
        Self {
            widget_ir_diagnostics: false,
            runtime_fuel_per_call: 10_000_000,
            max_module_bytes: 16 * 1_024 * 1_024,
            runtime_max_memory_pages: 64,
            runtime_max_table_elements: 1_024,
            runtime_max_call_depth: 256,
            protocol_max_chunk_bytes: 64 * 1_024,
            protocol_max_diagnostic_bytes: 64 * 1_024,
            protocol_max_terminal_results: 4,
            protocol_io_timeout_ms: 10_000,
            listener_credential_ttl_ms: 8 * 60 * 60 * 1_000,
            listener_max_authentication_failures: 4,
            listener_authentication_backoff_ms: 1_000,
            model_max_document_bytes: 4_096,
            model_max_state_entries: 32,
            model_max_widget_nodes: 128,
            model_max_properties: 128,
            model_max_widget_depth: 16,
            generation_max_retired: 4,
            max_callback_bindings: 8,
            state_transfer_migration_fuel: 10_000_000,
            reload_command_queue_capacity: 1,
            event_queue_capacity: 8,
        }
    }

    /// Returns the canonical text format version emitted for this profile.
    #[inline]
    pub const fn version(self) -> u64 {
        DEVELOPMENT_HOST_CONFIG_VERSION
    }

    /// Sets whether the host emits cross-platform Widget IR diagnostics.
    ///
    /// Diagnostics are disabled in [`Self::cli_safe_profile`]. Enabling them
    /// requests additional diagnostic output without changing any resource
    /// ceiling in this profile.
    #[inline]
    pub const fn widget_ir_diagnostics(mut self, enabled: bool) -> Self {
        self.widget_ir_diagnostics = enabled;
        self
    }

    /// Returns whether cross-platform Widget IR diagnostics are enabled.
    ///
    /// The canonical text representation encodes this value strictly as `0`
    /// when disabled and `1` when enabled.
    #[inline]
    pub const fn widget_ir_diagnostics_enabled(self) -> bool {
        self.widget_ir_diagnostics
    }

    /// Validates every ceiling and relationship in this profile.
    ///
    /// Individual ceilings must be nonzero and within their documented builder
    /// ranges. The protocol chunk and model document ceilings must also not
    /// exceed the complete module ceiling, and widget depth must not exceed the
    /// widget count ceiling.
    pub fn validate(self) -> Result<Self, DevelopmentHostConfigError> {
        validate_range("runtime_fuel_per_call", self.runtime_fuel_per_call, 1, MAX_FUEL)?;
        validate_range(
            "max_module_bytes",
            self.max_module_bytes as u64,
            1,
            MAX_MODULE_BYTES,
        )?;
        validate_range(
            "runtime_max_memory_pages",
            self.runtime_max_memory_pages as u64,
            1,
            MAX_MEMORY_PAGES,
        )?;
        validate_range(
            "runtime_max_table_elements",
            self.runtime_max_table_elements as u64,
            1,
            MAX_TABLE_ELEMENTS,
        )?;
        validate_range(
            "runtime_max_call_depth",
            self.runtime_max_call_depth as u64,
            1,
            MAX_CALL_DEPTH,
        )?;
        validate_range(
            "protocol_max_chunk_bytes",
            self.protocol_max_chunk_bytes as u64,
            1,
            MAX_CHUNK_BYTES,
        )?;
        validate_range(
            "protocol_max_diagnostic_bytes",
            self.protocol_max_diagnostic_bytes as u64,
            1,
            MAX_DIAGNOSTIC_BYTES,
        )?;
        validate_range(
            "protocol_max_terminal_results",
            self.protocol_max_terminal_results as u64,
            1,
            MAX_TERMINAL_RESULTS,
        )?;
        validate_range(
            "protocol_io_timeout_ms",
            self.protocol_io_timeout_ms,
            1,
            MAX_IO_TIMEOUT_MS,
        )?;
        validate_range(
            "listener_credential_ttl_ms",
            self.listener_credential_ttl_ms,
            1,
            MAX_CREDENTIAL_TTL_MS,
        )?;
        validate_range(
            "listener_max_authentication_failures",
            self.listener_max_authentication_failures as u64,
            1,
            MAX_AUTHENTICATION_FAILURES,
        )?;
        validate_range(
            "listener_authentication_backoff_ms",
            self.listener_authentication_backoff_ms,
            1,
            MAX_AUTHENTICATION_BACKOFF_MS,
        )?;
        validate_range(
            "model_max_document_bytes",
            self.model_max_document_bytes as u64,
            1,
            MAX_MODEL_DOCUMENT_BYTES,
        )?;
        validate_range(
            "model_max_state_entries",
            self.model_max_state_entries as u64,
            1,
            MAX_MODEL_ITEMS,
        )?;
        validate_range(
            "model_max_widget_nodes",
            self.model_max_widget_nodes as u64,
            1,
            MAX_MODEL_ITEMS,
        )?;
        validate_range(
            "model_max_properties",
            self.model_max_properties as u64,
            1,
            MAX_MODEL_PROPERTIES,
        )?;
        validate_range(
            "model_max_widget_depth",
            self.model_max_widget_depth as u64,
            1,
            MAX_WIDGET_DEPTH,
        )?;
        validate_range(
            "generation_max_retired",
            self.generation_max_retired as u64,
            1,
            MAX_RETIRED_GENERATIONS,
        )?;
        validate_range(
            "max_callback_bindings",
            self.max_callback_bindings as u64,
            1,
            MAX_CALLBACK_BINDINGS,
        )?;
        validate_range(
            "state_transfer_migration_fuel",
            self.state_transfer_migration_fuel,
            1,
            MAX_FUEL,
        )?;
        validate_range(
            "reload_command_queue_capacity",
            self.reload_command_queue_capacity as u64,
            1,
            MAX_QUEUE_CAPACITY,
        )?;
        validate_range(
            "event_queue_capacity",
            self.event_queue_capacity as u64,
            1,
            MAX_QUEUE_CAPACITY,
        )?;
        validate_not_greater(
            "protocol_max_chunk_bytes",
            self.protocol_max_chunk_bytes as u64,
            "max_module_bytes",
            self.max_module_bytes as u64,
        )?;
        validate_not_greater(
            "model_max_document_bytes",
            self.model_max_document_bytes as u64,
            "max_module_bytes",
            self.max_module_bytes as u64,
        )?;
        validate_not_greater(
            "model_max_widget_depth",
            self.model_max_widget_depth as u64,
            "model_max_widget_nodes",
            self.model_max_widget_nodes as u64,
        )?;
        Ok(self)
    }

    /// Serializes this profile into canonical version-1 key/value text.
    ///
    /// Keys always appear in the same order, decimal integers have no leading
    /// sign, and every record ends in a line feed. Invalid programmatic profiles
    /// are rejected rather than serialized.
    pub fn to_text(self) -> Result<String, DevelopmentHostConfigError> {
        let config = self.validate()?;
        let mut text = String::with_capacity(768);
        write!(
            text,
            concat!(
                "version={}\n",
                "widget_ir_diagnostics={}\n",
                "runtime_fuel_per_call={}\n",
                "max_module_bytes={}\n",
                "runtime_max_memory_pages={}\n",
                "runtime_max_table_elements={}\n",
                "runtime_max_call_depth={}\n",
                "protocol_max_chunk_bytes={}\n",
                "protocol_max_diagnostic_bytes={}\n",
                "protocol_max_terminal_results={}\n",
                "protocol_io_timeout_ms={}\n",
                "listener_credential_ttl_ms={}\n",
                "listener_max_authentication_failures={}\n",
                "listener_authentication_backoff_ms={}\n",
                "model_max_document_bytes={}\n",
                "model_max_state_entries={}\n",
                "model_max_widget_nodes={}\n",
                "model_max_properties={}\n",
                "model_max_widget_depth={}\n",
                "generation_max_retired={}\n",
                "max_callback_bindings={}\n",
                "state_transfer_migration_fuel={}\n",
                "reload_command_queue_capacity={}\n",
                "event_queue_capacity={}\n",
            ),
            DEVELOPMENT_HOST_CONFIG_VERSION,
            u8::from(config.widget_ir_diagnostics),
            config.runtime_fuel_per_call,
            config.max_module_bytes,
            config.runtime_max_memory_pages,
            config.runtime_max_table_elements,
            config.runtime_max_call_depth,
            config.protocol_max_chunk_bytes,
            config.protocol_max_diagnostic_bytes,
            config.protocol_max_terminal_results,
            config.protocol_io_timeout_ms,
            config.listener_credential_ttl_ms,
            config.listener_max_authentication_failures,
            config.listener_authentication_backoff_ms,
            config.model_max_document_bytes,
            config.model_max_state_entries,
            config.model_max_widget_nodes,
            config.model_max_properties,
            config.model_max_widget_depth,
            config.generation_max_retired,
            config.max_callback_bindings,
            config.state_transfer_migration_fuel,
            config.reload_command_queue_capacity,
            config.event_queue_capacity,
        )
        .expect("writing to a String cannot fail");
        if text.len() > MAX_DEVELOPMENT_HOST_CONFIG_TEXT_BYTES {
            return Err(DevelopmentHostConfigError::TextTooLong {
                actual: text.len(),
                maximum: MAX_DEVELOPMENT_HOST_CONFIG_TEXT_BYTES,
            });
        }
        Ok(text)
    }

    /// Parses one complete canonical development-host configuration.
    ///
    /// Input is rejected before field processing when it exceeds
    /// [`MAX_DEVELOPMENT_HOST_CONFIG_TEXT_BYTES`]. Every version-1 field must
    /// occur exactly once and contain an unsigned canonical decimal integer.
    /// The Widget IR diagnostic flag accepts only `0` or `1`.
    #[inline]
    pub fn from_text(text: &str) -> Result<Self, DevelopmentHostConfigError> {
        parse_config(text)
    }

    config_accessors! {
        runtime_fuel_per_call => runtime_fuel_per_call_limit: u64 => "Sets the guest execution fuel allowed for one call (1..=1,000,000,000).",
        max_module_bytes => module_bytes_limit: usize => "Sets the complete guest module ceiling in bytes (1..=268,435,456).",
        runtime_max_memory_pages => runtime_memory_pages_limit: u32 => "Sets the guest linear-memory page ceiling (1..=65,536).",
        runtime_max_table_elements => runtime_table_elements_limit: u32 => "Sets the guest table-element ceiling (1..=1,000,000).",
        runtime_max_call_depth => runtime_call_depth_limit: u32 => "Sets the guest call-depth ceiling (1..=65,536).",
        protocol_max_chunk_bytes => protocol_chunk_bytes_limit: usize => "Sets the plaintext frame chunk ceiling in bytes (1..=16,777,216 and no larger than the module ceiling).",
        protocol_max_diagnostic_bytes => protocol_diagnostic_bytes_limit: usize => "Sets the terminal diagnostic ceiling in bytes (1..=1,048,576).",
        protocol_max_terminal_results => protocol_terminal_result_limit: usize => "Sets the retained terminal-result count (1..=1,024).",
        protocol_io_timeout_ms => protocol_io_timeout_ms_limit: u64 => "Sets the per-connection I/O timeout in milliseconds (1..=300,000).",
        listener_credential_ttl_ms => listener_credential_ttl_ms_limit: u64 => "Sets the listener credential lifetime in milliseconds (1..=86,400,000).",
        listener_max_authentication_failures => listener_authentication_failure_limit: u32 => "Sets the authentication-failure allowance (1..=1,024).",
        listener_authentication_backoff_ms => listener_authentication_backoff_ms_limit: u64 => "Sets the authentication backoff in milliseconds (1..=60,000).",
        model_max_document_bytes => model_document_bytes_limit: usize => "Sets the portable-model document ceiling in bytes (1..=67,108,864 and no larger than the module ceiling).",
        model_max_state_entries => model_state_entry_limit: u32 => "Sets the portable-state entry ceiling (1..=1,000,000).",
        model_max_widget_nodes => model_widget_node_limit: u32 => "Sets the portable widget-node ceiling (1..=1,000,000).",
        model_max_properties => model_property_limit: u32 => "Sets the portable property ceiling (1..=4,000,000).",
        model_max_widget_depth => model_widget_depth_limit: u32 => "Sets the portable widget-depth ceiling (1..=4,096 and no larger than the widget-node ceiling).",
        generation_max_retired => retired_generation_limit: usize => "Sets the retained retired-generation ceiling (1..=1,024).",
        max_callback_bindings => callback_binding_limit: u32 => "Sets the callback-binding ceiling per generation (1..=1,000,000).",
        state_transfer_migration_fuel => state_transfer_migration_fuel_limit: u64 => "Sets the state-migration fuel ceiling (1..=1,000,000,000).",
        reload_command_queue_capacity => reload_command_queue_capacity_limit: usize => "Sets the authenticated reload-command queue capacity (1..=65,536).",
        event_queue_capacity => event_queue_capacity_limit: usize => "Sets the event-barrier queue capacity (1..=65,536).",
    }
}

fn validate_range(
    field: &'static str,
    value: u64,
    minimum: u64,
    maximum: u64,
) -> Result<(), DevelopmentHostConfigError> {
    if !(minimum..=maximum).contains(&value) {
        return Err(DevelopmentHostConfigError::OutOfRange {
            field,
            value,
            minimum,
            maximum,
        });
    }
    Ok(())
}

fn validate_not_greater(
    field: &'static str,
    value: u64,
    maximum_field: &'static str,
    maximum: u64,
) -> Result<(), DevelopmentHostConfigError> {
    if value > maximum {
        return Err(DevelopmentHostConfigError::ExceedsField {
            field,
            maximum_field,
        });
    }
    Ok(())
}

/// Failure while parsing, validating, or serializing host configuration text.
///
/// Unknown field names and malformed line contents are intentionally omitted
/// from error values so diagnostics cannot echo a mistakenly supplied secret.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DevelopmentHostConfigError {
    /// Input exceeded [`MAX_DEVELOPMENT_HOST_CONFIG_TEXT_BYTES`].
    TextTooLong { actual: usize, maximum: usize },
    /// A line was empty or was not exactly one key/value record.
    MalformedLine,
    /// A format version is not supported by this implementation.
    UnsupportedVersion(u64),
    /// A required field was absent.
    MissingField(&'static str),
    /// A field occurred more than once.
    DuplicateField(&'static str),
    /// A key is not part of the current format.
    UnknownField,
    /// A known field was not an unsigned decimal integer.
    MalformedValue(&'static str),
    /// A value was outside its inclusive safety range.
    OutOfRange {
        field: &'static str,
        value: u64,
        minimum: u64,
        maximum: u64,
    },
    /// A ceiling exceeded another ceiling that contains it.
    ExceedsField {
        field: &'static str,
        maximum_field: &'static str,
    },
}

impl fmt::Display for DevelopmentHostConfigError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::TextTooLong { actual, maximum } => write!(
                formatter,
                "development host configuration is {actual} bytes but the limit is {maximum}"
            ),
            Self::MalformedLine => {
                formatter.write_str("development host configuration contains a malformed line")
            }
            Self::UnsupportedVersion(version) => {
                write!(formatter, "unsupported development host configuration version {version}")
            }
            Self::MissingField(field) => write!(
                formatter,
                "development host configuration is missing field {field}"
            ),
            Self::DuplicateField(field) => write!(
                formatter,
                "development host configuration repeats field {field}"
            ),
            Self::UnknownField => {
                formatter.write_str("development host configuration contains an unknown field")
            }
            Self::MalformedValue(field) => write!(
                formatter,
                "development host configuration field {field} is malformed"
            ),
            Self::OutOfRange {
                field,
                value,
                minimum,
                maximum,
            } => write!(
                formatter,
                "development host configuration field {field} is {value}, outside {minimum}..={maximum}"
            ),
            Self::ExceedsField {
                field,
                maximum_field,
            } => write!(
                formatter,
                "development host configuration field {field} exceeds {maximum_field}"
            ),
        }
    }
}

impl Error for DevelopmentHostConfigError {}

impl FromStr for DevelopmentHostConfig {
    type Err = DevelopmentHostConfigError;

    fn from_str(text: &str) -> Result<Self, Self::Err> {
        Self::from_text(text)
    }
}

fn parse_config(text: &str) -> Result<DevelopmentHostConfig, DevelopmentHostConfigError> {
    if text.len() > MAX_DEVELOPMENT_HOST_CONFIG_TEXT_BYTES {
        return Err(DevelopmentHostConfigError::TextTooLong {
            actual: text.len(),
            maximum: MAX_DEVELOPMENT_HOST_CONFIG_TEXT_BYTES,
        });
    }

    let mut values = ParsedValues::new();
    for line in text.lines() {
        if line.is_empty() {
            return Err(DevelopmentHostConfigError::MalformedLine);
        }
        let Some((key, value)) = line.split_once('=') else {
            return Err(DevelopmentHostConfigError::MalformedLine);
        };
        if key.is_empty() || value.is_empty() || value.contains('=') {
            return Err(DevelopmentHostConfigError::MalformedLine);
        }
        values.set(key, value)?;
    }
    values.finish()
}

struct ParsedValues {
    version: Option<u64>,
    widget_ir_diagnostics: Option<u64>,
    runtime_fuel_per_call: Option<u64>,
    max_module_bytes: Option<u64>,
    runtime_max_memory_pages: Option<u64>,
    runtime_max_table_elements: Option<u64>,
    runtime_max_call_depth: Option<u64>,
    protocol_max_chunk_bytes: Option<u64>,
    protocol_max_diagnostic_bytes: Option<u64>,
    protocol_max_terminal_results: Option<u64>,
    protocol_io_timeout_ms: Option<u64>,
    listener_credential_ttl_ms: Option<u64>,
    listener_max_authentication_failures: Option<u64>,
    listener_authentication_backoff_ms: Option<u64>,
    model_max_document_bytes: Option<u64>,
    model_max_state_entries: Option<u64>,
    model_max_widget_nodes: Option<u64>,
    model_max_properties: Option<u64>,
    model_max_widget_depth: Option<u64>,
    generation_max_retired: Option<u64>,
    max_callback_bindings: Option<u64>,
    state_transfer_migration_fuel: Option<u64>,
    reload_command_queue_capacity: Option<u64>,
    event_queue_capacity: Option<u64>,
}

macro_rules! parsed_fields {
    ($macro:ident) => {
        $macro! {
            version,
            widget_ir_diagnostics,
            runtime_fuel_per_call,
            max_module_bytes,
            runtime_max_memory_pages,
            runtime_max_table_elements,
            runtime_max_call_depth,
            protocol_max_chunk_bytes,
            protocol_max_diagnostic_bytes,
            protocol_max_terminal_results,
            protocol_io_timeout_ms,
            listener_credential_ttl_ms,
            listener_max_authentication_failures,
            listener_authentication_backoff_ms,
            model_max_document_bytes,
            model_max_state_entries,
            model_max_widget_nodes,
            model_max_properties,
            model_max_widget_depth,
            generation_max_retired,
            max_callback_bindings,
            state_transfer_migration_fuel,
            reload_command_queue_capacity,
            event_queue_capacity,
        }
    };
    ($macro:ident, $self:ident, $key:ident, $value:ident) => {
        $macro! {
            $self, $key, $value;
            version,
            widget_ir_diagnostics,
            runtime_fuel_per_call,
            max_module_bytes,
            runtime_max_memory_pages,
            runtime_max_table_elements,
            runtime_max_call_depth,
            protocol_max_chunk_bytes,
            protocol_max_diagnostic_bytes,
            protocol_max_terminal_results,
            protocol_io_timeout_ms,
            listener_credential_ttl_ms,
            listener_max_authentication_failures,
            listener_authentication_backoff_ms,
            model_max_document_bytes,
            model_max_state_entries,
            model_max_widget_nodes,
            model_max_properties,
            model_max_widget_depth,
            generation_max_retired,
            max_callback_bindings,
            state_transfer_migration_fuel,
            reload_command_queue_capacity,
            event_queue_capacity,
        }
    };
}

macro_rules! initialize_parsed_fields {
    ($( $field:ident, )+) => {
        Self { $( $field: None, )+ }
    };
}

macro_rules! set_parsed_field {
    ($self:ident, $key:ident, $value:ident; $( $field:ident, )+) => {
        match $key {
            $(
                stringify!($field) => set_once(
                    &mut $self.$field,
                    stringify!($field),
                    $value,
                ),
            )+
            _ => Err(DevelopmentHostConfigError::UnknownField),
        }
    };
}

impl ParsedValues {
    const fn new() -> Self {
        parsed_fields!(initialize_parsed_fields)
    }

    fn set(&mut self, key: &str, value: &str) -> Result<(), DevelopmentHostConfigError> {
        parsed_fields!(set_parsed_field, self, key, value)
    }

    fn finish(self) -> Result<DevelopmentHostConfig, DevelopmentHostConfigError> {
        let version = required(self.version, "version")?;
        if version != DEVELOPMENT_HOST_CONFIG_VERSION {
            return Err(DevelopmentHostConfigError::UnsupportedVersion(version));
        }
        let config = DevelopmentHostConfig {
            widget_ir_diagnostics: strict_bool(
                required(self.widget_ir_diagnostics, "widget_ir_diagnostics")?,
                "widget_ir_diagnostics",
            )?,
            runtime_fuel_per_call: required(
                self.runtime_fuel_per_call,
                "runtime_fuel_per_call",
            )?,
            max_module_bytes: bounded_usize(
                required(self.max_module_bytes, "max_module_bytes")?,
                "max_module_bytes",
                MAX_MODULE_BYTES,
            )?,
            runtime_max_memory_pages: bounded_u32(
                required(self.runtime_max_memory_pages, "runtime_max_memory_pages")?,
                "runtime_max_memory_pages",
                MAX_MEMORY_PAGES,
            )?,
            runtime_max_table_elements: bounded_u32(
                required(
                    self.runtime_max_table_elements,
                    "runtime_max_table_elements",
                )?,
                "runtime_max_table_elements",
                MAX_TABLE_ELEMENTS,
            )?,
            runtime_max_call_depth: bounded_u32(
                required(self.runtime_max_call_depth, "runtime_max_call_depth")?,
                "runtime_max_call_depth",
                MAX_CALL_DEPTH,
            )?,
            protocol_max_chunk_bytes: bounded_usize(
                required(
                    self.protocol_max_chunk_bytes,
                    "protocol_max_chunk_bytes",
                )?,
                "protocol_max_chunk_bytes",
                MAX_CHUNK_BYTES,
            )?,
            protocol_max_diagnostic_bytes: bounded_usize(
                required(
                    self.protocol_max_diagnostic_bytes,
                    "protocol_max_diagnostic_bytes",
                )?,
                "protocol_max_diagnostic_bytes",
                MAX_DIAGNOSTIC_BYTES,
            )?,
            protocol_max_terminal_results: bounded_usize(
                required(
                    self.protocol_max_terminal_results,
                    "protocol_max_terminal_results",
                )?,
                "protocol_max_terminal_results",
                MAX_TERMINAL_RESULTS,
            )?,
            protocol_io_timeout_ms: required(
                self.protocol_io_timeout_ms,
                "protocol_io_timeout_ms",
            )?,
            listener_credential_ttl_ms: required(
                self.listener_credential_ttl_ms,
                "listener_credential_ttl_ms",
            )?,
            listener_max_authentication_failures: bounded_u32(
                required(
                    self.listener_max_authentication_failures,
                    "listener_max_authentication_failures",
                )?,
                "listener_max_authentication_failures",
                MAX_AUTHENTICATION_FAILURES,
            )?,
            listener_authentication_backoff_ms: required(
                self.listener_authentication_backoff_ms,
                "listener_authentication_backoff_ms",
            )?,
            model_max_document_bytes: bounded_usize(
                required(
                    self.model_max_document_bytes,
                    "model_max_document_bytes",
                )?,
                "model_max_document_bytes",
                MAX_MODEL_DOCUMENT_BYTES,
            )?,
            model_max_state_entries: bounded_u32(
                required(self.model_max_state_entries, "model_max_state_entries")?,
                "model_max_state_entries",
                MAX_MODEL_ITEMS,
            )?,
            model_max_widget_nodes: bounded_u32(
                required(self.model_max_widget_nodes, "model_max_widget_nodes")?,
                "model_max_widget_nodes",
                MAX_MODEL_ITEMS,
            )?,
            model_max_properties: bounded_u32(
                required(self.model_max_properties, "model_max_properties")?,
                "model_max_properties",
                MAX_MODEL_PROPERTIES,
            )?,
            model_max_widget_depth: bounded_u32(
                required(self.model_max_widget_depth, "model_max_widget_depth")?,
                "model_max_widget_depth",
                MAX_WIDGET_DEPTH,
            )?,
            generation_max_retired: bounded_usize(
                required(self.generation_max_retired, "generation_max_retired")?,
                "generation_max_retired",
                MAX_RETIRED_GENERATIONS,
            )?,
            max_callback_bindings: bounded_u32(
                required(self.max_callback_bindings, "max_callback_bindings")?,
                "max_callback_bindings",
                MAX_CALLBACK_BINDINGS,
            )?,
            state_transfer_migration_fuel: required(
                self.state_transfer_migration_fuel,
                "state_transfer_migration_fuel",
            )?,
            reload_command_queue_capacity: bounded_usize(
                required(
                    self.reload_command_queue_capacity,
                    "reload_command_queue_capacity",
                )?,
                "reload_command_queue_capacity",
                MAX_QUEUE_CAPACITY,
            )?,
            event_queue_capacity: bounded_usize(
                required(self.event_queue_capacity, "event_queue_capacity")?,
                "event_queue_capacity",
                MAX_QUEUE_CAPACITY,
            )?,
        };
        config.validate()
    }
}

fn set_once(
    slot: &mut Option<u64>,
    field: &'static str,
    value: &str,
) -> Result<(), DevelopmentHostConfigError> {
    if slot.is_some() {
        return Err(DevelopmentHostConfigError::DuplicateField(field));
    }
    if !value.bytes().all(|byte| byte.is_ascii_digit())
        || (value.len() > 1 && value.starts_with('0'))
    {
        return Err(DevelopmentHostConfigError::MalformedValue(field));
    }
    let parsed = value
        .parse::<u64>()
        .map_err(|_| DevelopmentHostConfigError::MalformedValue(field))?;
    *slot = Some(parsed);
    Ok(())
}

fn required(
    value: Option<u64>,
    field: &'static str,
) -> Result<u64, DevelopmentHostConfigError> {
    value.ok_or(DevelopmentHostConfigError::MissingField(field))
}

fn strict_bool(
    value: u64,
    field: &'static str,
) -> Result<bool, DevelopmentHostConfigError> {
    match value {
        0 => Ok(false),
        1 => Ok(true),
        _ => Err(DevelopmentHostConfigError::MalformedValue(field)),
    }
}

fn bounded_usize(
    value: u64,
    field: &'static str,
    maximum: u64,
) -> Result<usize, DevelopmentHostConfigError> {
    validate_range(field, value, 1, maximum)?;
    Ok(value as usize)
}

fn bounded_u32(
    value: u64,
    field: &'static str,
    maximum: u64,
) -> Result<u32, DevelopmentHostConfigError> {
    validate_range(field, value, 1, maximum)?;
    Ok(value as u32)
}

#[cfg(test)]
mod tests {
    use super::*;

    const CLI_SAFE_TEXT: &str = concat!(
        "version=1\n",
        "widget_ir_diagnostics=0\n",
        "runtime_fuel_per_call=10000000\n",
        "max_module_bytes=16777216\n",
        "runtime_max_memory_pages=64\n",
        "runtime_max_table_elements=1024\n",
        "runtime_max_call_depth=256\n",
        "protocol_max_chunk_bytes=65536\n",
        "protocol_max_diagnostic_bytes=65536\n",
        "protocol_max_terminal_results=4\n",
        "protocol_io_timeout_ms=10000\n",
        "listener_credential_ttl_ms=28800000\n",
        "listener_max_authentication_failures=4\n",
        "listener_authentication_backoff_ms=1000\n",
        "model_max_document_bytes=4096\n",
        "model_max_state_entries=32\n",
        "model_max_widget_nodes=128\n",
        "model_max_properties=128\n",
        "model_max_widget_depth=16\n",
        "generation_max_retired=4\n",
        "max_callback_bindings=8\n",
        "state_transfer_migration_fuel=10000000\n",
        "reload_command_queue_capacity=1\n",
        "event_queue_capacity=8\n",
    );

    #[test]
    fn cli_safe_profile_has_stable_versioned_text_and_round_trips() {
        let config = DevelopmentHostConfig::cli_safe_profile();

        assert_eq!(config.to_text().unwrap(), CLI_SAFE_TEXT);
        assert!(!CLI_SAFE_TEXT.contains("session_id"));
        assert!(!CLI_SAFE_TEXT.contains("session_token"));
        assert_eq!(CLI_SAFE_TEXT.parse::<DevelopmentHostConfig>().unwrap(), config);
        assert_eq!(DevelopmentHostConfig::from_text(CLI_SAFE_TEXT).unwrap(), config);
        assert_eq!(config.version(), DEVELOPMENT_HOST_CONFIG_VERSION);
        assert_eq!(config.runtime_fuel_per_call_limit(), 10_000_000);
        assert_eq!(config.module_bytes_limit(), 16 * 1_024 * 1_024);
        assert_eq!(config.runtime_memory_pages_limit(), 64);
        assert_eq!(config.runtime_table_elements_limit(), 1_024);
        assert_eq!(config.runtime_call_depth_limit(), 256);
        assert_eq!(config.protocol_chunk_bytes_limit(), 64 * 1_024);
        assert_eq!(config.protocol_diagnostic_bytes_limit(), 64 * 1_024);
        assert_eq!(config.protocol_terminal_result_limit(), 4);
        assert_eq!(config.protocol_io_timeout_ms_limit(), 10_000);
        assert_eq!(config.listener_credential_ttl_ms_limit(), 28_800_000);
        assert_eq!(config.listener_authentication_failure_limit(), 4);
        assert_eq!(config.listener_authentication_backoff_ms_limit(), 1_000);
        assert_eq!(config.model_document_bytes_limit(), 4_096);
        assert_eq!(config.model_state_entry_limit(), 32);
        assert_eq!(config.model_widget_node_limit(), 128);
        assert_eq!(config.model_property_limit(), 128);
        assert_eq!(config.model_widget_depth_limit(), 16);
        assert_eq!(config.retired_generation_limit(), 4);
        assert_eq!(config.callback_binding_limit(), 8);
        assert_eq!(config.state_transfer_migration_fuel_limit(), 10_000_000);
        assert_eq!(config.reload_command_queue_capacity_limit(), 1);
        assert_eq!(config.event_queue_capacity_limit(), 8);
    }

    #[test]
    fn widget_ir_diagnostics_are_explicit_strict_and_round_trip() {
        let disabled = DevelopmentHostConfig::cli_safe_profile();
        let enabled = disabled.widget_ir_diagnostics(true);
        let enabled_text = CLI_SAFE_TEXT.replacen(
            "widget_ir_diagnostics=0",
            "widget_ir_diagnostics=1",
            1,
        );

        assert!(!disabled.widget_ir_diagnostics_enabled());
        assert!(enabled.widget_ir_diagnostics_enabled());
        assert_eq!(disabled.to_text().unwrap(), CLI_SAFE_TEXT);
        assert_eq!(enabled.to_text().unwrap(), enabled_text);
        assert_eq!(CLI_SAFE_TEXT.parse::<DevelopmentHostConfig>().unwrap(), disabled);
        assert_eq!(enabled_text.parse::<DevelopmentHostConfig>().unwrap(), enabled);
        assert_eq!(disabled.validate().unwrap(), disabled);
        assert_eq!(enabled.validate().unwrap(), enabled);

        let missing = CLI_SAFE_TEXT.replacen("widget_ir_diagnostics=0\n", "", 1);
        let duplicate = format!("{CLI_SAFE_TEXT}widget_ir_diagnostics=0\n");
        assert!(matches!(
            missing.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::MissingField("widget_ir_diagnostics"))
        ));
        assert!(matches!(
            duplicate.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::DuplicateField("widget_ir_diagnostics"))
        ));
        for malformed in ["2", "true", "01"] {
            let text = CLI_SAFE_TEXT.replacen(
                "widget_ir_diagnostics=0",
                &format!("widget_ir_diagnostics={malformed}"),
                1,
            );
            assert!(matches!(
                text.parse::<DevelopmentHostConfig>(),
                Err(DevelopmentHostConfigError::MalformedValue("widget_ir_diagnostics"))
            ));
        }
    }

    #[test]
    fn parser_rejects_missing_duplicate_unknown_and_malformed_fields() {
        let missing = CLI_SAFE_TEXT.replacen("event_queue_capacity=8\n", "", 1);
        let duplicate = format!("{CLI_SAFE_TEXT}event_queue_capacity=8\n");
        let unknown = format!("{CLI_SAFE_TEXT}session_token=secret\n");
        let malformed = CLI_SAFE_TEXT.replacen(
            "event_queue_capacity=8",
            "event_queue_capacity=not-a-number",
            1,
        );

        assert!(matches!(
            missing.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::MissingField("event_queue_capacity"))
        ));
        assert!(matches!(
            duplicate.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::DuplicateField("event_queue_capacity"))
        ));
        assert!(matches!(
            unknown.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::UnknownField)
        ));
        assert!(matches!(
            malformed.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::MalformedValue("event_queue_capacity"))
        ));
        let secret_error = unknown.parse::<DevelopmentHostConfig>().unwrap_err();
        assert!(!format!("{secret_error:?} {secret_error}").contains("secret"));
        for noncanonical in ["+8", "08", " 8", "8 "] {
            let text = CLI_SAFE_TEXT.replacen(
                "event_queue_capacity=8",
                &format!("event_queue_capacity={noncanonical}"),
                1,
            );
            assert!(matches!(
                text.parse::<DevelopmentHostConfig>(),
                Err(DevelopmentHostConfigError::MalformedValue("event_queue_capacity"))
            ));
        }
    }

    #[test]
    fn parser_rejects_unknown_versions_zeroes_and_out_of_range_values() {
        let unknown_version = CLI_SAFE_TEXT.replacen("version=1", "version=2", 1);
        let zero = CLI_SAFE_TEXT.replacen("event_queue_capacity=8", "event_queue_capacity=0", 1);
        let out_of_range = CLI_SAFE_TEXT.replacen(
            "runtime_max_memory_pages=64",
            "runtime_max_memory_pages=65537",
            1,
        );
        let wider_than_destination = CLI_SAFE_TEXT.replacen(
            "runtime_max_memory_pages=64",
            "runtime_max_memory_pages=4294967296",
            1,
        );
        let inconsistent = CLI_SAFE_TEXT.replacen(
            "max_module_bytes=16777216",
            "max_module_bytes=65535",
            1,
        );

        assert!(matches!(
            unknown_version.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::UnsupportedVersion(2))
        ));
        assert!(matches!(
            zero.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::OutOfRange {
                field: "event_queue_capacity",
                value: 0,
                minimum: 1,
                maximum: 65_536,
            })
        ));
        assert!(matches!(
            out_of_range.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::OutOfRange {
                field: "runtime_max_memory_pages",
                value: 65_537,
                minimum: 1,
                maximum: 65_536,
            })
        ));
        assert!(matches!(
            wider_than_destination.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::OutOfRange {
                field: "runtime_max_memory_pages",
                value: 4_294_967_296,
                minimum: 1,
                maximum: 65_536,
            })
        ));
        assert!(matches!(
            inconsistent.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::ExceedsField {
                field: "protocol_max_chunk_bytes",
                maximum_field: "max_module_bytes",
            })
        ));
    }

    #[test]
    fn parser_bounds_input_before_processing_fields() {
        let oversized = "x".repeat(MAX_DEVELOPMENT_HOST_CONFIG_TEXT_BYTES + 1);

        assert!(matches!(
            oversized.parse::<DevelopmentHostConfig>(),
            Err(DevelopmentHostConfigError::TextTooLong { .. })
        ));
    }

    #[test]
    fn serialization_revalidates_programmatic_profiles() {
        let invalid = DevelopmentHostConfig::cli_safe_profile().event_queue_capacity(0);

        assert!(matches!(
            invalid.to_text(),
            Err(DevelopmentHostConfigError::OutOfRange {
                field: "event_queue_capacity",
                value: 0,
                minimum: 1,
                maximum: 65_536,
            })
        ));
    }

    #[test]
    fn every_programmatic_ceiling_rejects_zero_and_values_above_its_range() {
        type Setter = fn(DevelopmentHostConfig, u64) -> DevelopmentHostConfig;
        let cases: [(&str, u64, Setter); 22] = [
            ("runtime_fuel_per_call", MAX_FUEL, |config, value| {
                config.runtime_fuel_per_call(value)
            }),
            ("max_module_bytes", MAX_MODULE_BYTES, |config, value| {
                config.max_module_bytes(value as usize)
            }),
            ("runtime_max_memory_pages", MAX_MEMORY_PAGES, |config, value| {
                config.runtime_max_memory_pages(value as u32)
            }),
            ("runtime_max_table_elements", MAX_TABLE_ELEMENTS, |config, value| {
                config.runtime_max_table_elements(value as u32)
            }),
            ("runtime_max_call_depth", MAX_CALL_DEPTH, |config, value| {
                config.runtime_max_call_depth(value as u32)
            }),
            ("protocol_max_chunk_bytes", MAX_CHUNK_BYTES, |config, value| {
                config.protocol_max_chunk_bytes(value as usize)
            }),
            (
                "protocol_max_diagnostic_bytes",
                MAX_DIAGNOSTIC_BYTES,
                |config, value| config.protocol_max_diagnostic_bytes(value as usize),
            ),
            (
                "protocol_max_terminal_results",
                MAX_TERMINAL_RESULTS,
                |config, value| config.protocol_max_terminal_results(value as usize),
            ),
            ("protocol_io_timeout_ms", MAX_IO_TIMEOUT_MS, |config, value| {
                config.protocol_io_timeout_ms(value)
            }),
            (
                "listener_credential_ttl_ms",
                MAX_CREDENTIAL_TTL_MS,
                |config, value| config.listener_credential_ttl_ms(value),
            ),
            (
                "listener_max_authentication_failures",
                MAX_AUTHENTICATION_FAILURES,
                |config, value| config.listener_max_authentication_failures(value as u32),
            ),
            (
                "listener_authentication_backoff_ms",
                MAX_AUTHENTICATION_BACKOFF_MS,
                |config, value| config.listener_authentication_backoff_ms(value),
            ),
            (
                "model_max_document_bytes",
                MAX_MODEL_DOCUMENT_BYTES,
                |config, value| config.model_max_document_bytes(value as usize),
            ),
            ("model_max_state_entries", MAX_MODEL_ITEMS, |config, value| {
                config.model_max_state_entries(value as u32)
            }),
            ("model_max_widget_nodes", MAX_MODEL_ITEMS, |config, value| {
                config.model_max_widget_nodes(value as u32)
            }),
            ("model_max_properties", MAX_MODEL_PROPERTIES, |config, value| {
                config.model_max_properties(value as u32)
            }),
            ("model_max_widget_depth", MAX_WIDGET_DEPTH, |config, value| {
                config.model_max_widget_depth(value as u32)
            }),
            (
                "generation_max_retired",
                MAX_RETIRED_GENERATIONS,
                |config, value| config.generation_max_retired(value as usize),
            ),
            ("max_callback_bindings", MAX_CALLBACK_BINDINGS, |config, value| {
                config.max_callback_bindings(value as u32)
            }),
            ("state_transfer_migration_fuel", MAX_FUEL, |config, value| {
                config.state_transfer_migration_fuel(value)
            }),
            (
                "reload_command_queue_capacity",
                MAX_QUEUE_CAPACITY,
                |config, value| config.reload_command_queue_capacity(value as usize),
            ),
            ("event_queue_capacity", MAX_QUEUE_CAPACITY, |config, value| {
                config.event_queue_capacity(value as usize)
            }),
        ];

        for (field, maximum, setter) in cases {
            assert_eq!(
                setter(DevelopmentHostConfig::cli_safe_profile(), 0).validate(),
                Err(DevelopmentHostConfigError::OutOfRange {
                    field,
                    value: 0,
                    minimum: 1,
                    maximum,
                })
            );
            assert_eq!(
                setter(DevelopmentHostConfig::cli_safe_profile(), maximum + 1).validate(),
                Err(DevelopmentHostConfigError::OutOfRange {
                    field,
                    value: maximum + 1,
                    minimum: 1,
                    maximum,
                })
            );
        }
    }
}