[package]
name = "aimer_anteros"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = ["host-runtime"]
host-runtime = ["dep:aimer_venus"]
wasm-hot-reload = ["host-runtime", "dep:wasmi", "dep:wasmparser"]

[dependencies]
aimer_venus = { workspace = true, optional = true }
sha2.workspace = true
wasmi = { workspace = true, optional = true }
wasmparser = { workspace = true, optional = true }
