//! Android's night mode, read from the activity's configuration.
//!
//! winit answers `None` from `Window::theme()` on Android and never emits
//! `ThemeChanged`, so the appearance is taken from the same place the platform
//! keeps every other configuration value: `AConfiguration`, exposed by
//! `android-activity` as [`AndroidApp::config`].
//!
//! The user switching the system into dark mode is a configuration change. An
//! activity that does not declare `uiMode` in `android:configChanges` is
//! *destroyed and recreated* for it, and the appearance is then picked up on
//! the next start-up; one that declares it — as the manifest generated by
//! `aimer create` does — keeps running and is handed
//! `MainEvent::ConfigChanged`, which winit forwards as
//! [`winit::event::WindowEvent::ScaleFactorChanged`].
//!
//! [`AndroidApp::config`]: winit::platform::android::activity::AndroidApp::config

use aimer_widget::Brightness;

/// Reads the appearance from the running activity's configuration.
///
/// `None` before the activity has been handed to the framework, or when the
/// configuration pins no night mode.
pub fn current_appearance() -> Option<Brightness> {
    let app = crate::aimer_app::ANDROID_APP.get()?;
    let night_mode = i32::from(app.config().ui_mode_night());
    crate::system_appearance::from_night_mode(night_mode)
}
