import UIKit

// Rust entrypoint generated by `#[aimer_main]`.
@_silgen_name("__generated_entrance_point")
func __generated_entrance_point()

// Software keyboard forwarding into Rust.
@_silgen_name("trigger_rust_backspace")
func trigger_rust_backspace()

@_silgen_name("trigger_rust_insert_text")
func trigger_rust_insert_text(_ ptr: UnsafePointer<UInt8>, _ len: Int)

// Provisional text a multistage input method is still composing ("marked
// text" in UIKit's vocabulary). Rust paints it in the focused field the way a
// desktop `Ime::Preedit` is painted; an empty string ends the composition.
@_silgen_name("trigger_rust_set_marked_text")
func trigger_rust_set_marked_text(_ ptr: UnsafePointer<UInt8>, _ len: Int)

@_silgen_name("trigger_rust_text_editing_delta")
func trigger_rust_text_editing_delta(
    _ sessionId: UInt64,
    _ revision: UInt64,
    _ replaceStart: Int,
    _ replaceEnd: Int,
    _ utf8Ptr: UnsafePointer<UInt8>?,
    _ utf8Len: Int,
    _ selectionStart: Int,
    _ selectionEnd: Int,
    _ composingStart: Int,
    _ composingEnd: Int
)

@_cdecl("aimer_ios_show_keyboard")
func aimer_ios_show_keyboard() {
    DispatchQueue.main.async {
        KeyboardForwarder.shared.showKeyboard()
    }
}

@_cdecl("aimer_ios_dismiss_keyboard")
func aimer_ios_dismiss_keyboard() {
    DispatchQueue.main.async {
        KeyboardForwarder.shared.dismissKeyboard()
    }
}

// The language the software keyboard is typing in, as an IETF tag such as
// "zh-Hans" or "ja-JP". Han ideographs are shared by Chinese, Japanese and
// Korean but drawn with different faces, and the text alone cannot say which
// language it is written in — the keyboard that produced it can, so Rust asks
// for the tag on every keystroke that carries text. The answer is the value
// cached by `KeyboardForwarder`, so the call is a memcpy of at most `capacity`
// bytes; it returns the number of bytes written, or 0 when no keyboard is up
// or the tag does not fit.
@_cdecl("aimer_ios_input_language")
func aimer_ios_input_language(_ buffer: UnsafeMutablePointer<UInt8>?, _ capacity: Int) -> Int {
    guard let buffer, capacity > 0 else { return 0 }
    let utf8 = Array(KeyboardForwarder.shared.inputLanguageTag.utf8)
    guard !utf8.isEmpty, utf8.count <= capacity else { return 0 }
    utf8.withUnsafeBufferPointer { source in
        buffer.update(from: source.baseAddress!, count: source.count)
    }
    return utf8.count
}

@_cdecl("aimer_ios_sync_text_state")
func aimer_ios_sync_text_state(
    _ sessionId: UInt64,
    _ revision: UInt64,
    _ utf8Ptr: UnsafePointer<UInt8>?,
    _ utf8Len: Int,
    _ selectionStart: Int,
    _ selectionEnd: Int,
    _ composingStart: Int,
    _ composingEnd: Int,
    _ secure: Bool,
    _ inputKind: Int32
) {
    guard utf8Len >= 0, utf8Len == 0 || utf8Ptr != nil else { return }
    let text = utf8Len == 0
        ? ""
        : String(decoding: UnsafeBufferPointer(start: utf8Ptr!, count: utf8Len), as: UTF8.self)
    DispatchQueue.main.async {
        KeyboardForwarder.shared.syncTextState(
            sessionId: sessionId,
            revision: revision,
            text: text,
            selectionStart: selectionStart,
            selectionEnd: selectionEnd,
            composingStart: composingStart,
            composingEnd: composingEnd,
            secure: secure,
            inputKind: inputKind
        )
    }
}

// Frame scheduling into Rust.
// A CADisplayLink drives redraws in sync with the display (up to 120 fps on
// ProMotion). It stays paused while idle; Rust unpauses it when a frame is
// requested and pauses it again once no more frames are pending.
@_silgen_name("aimer_ios_frame_tick")
func aimer_ios_frame_tick()

final class FrameDriver {
    static let shared = FrameDriver()
    private var displayLink: CADisplayLink?

    func start() {
        guard displayLink == nil else { return }
        let link = CADisplayLink(target: self, selector: #selector(tick))
        if #available(iOS 15.0, *) {
            // Allow the system to run up to 120 Hz on ProMotion displays.
            link.preferredFrameRateRange = CAFrameRateRange(minimum: 80, maximum: 120, preferred: 120)
        }
        // Start paused; frames are produced on demand.
        link.isPaused = true
        link.add(to: .main, forMode: .common)
        displayLink = link
    }

    func requestFrame() {
        displayLink?.isPaused = false
    }

    func pause() {
        displayLink?.isPaused = true
    }

    @objc private func tick() {
        aimer_ios_frame_tick()
    }
}

@_cdecl("aimer_ios_request_frame")
func aimer_ios_request_frame() {
    DispatchQueue.main.async {
        FrameDriver.shared.requestFrame()
    }
}

@_cdecl("aimer_ios_pause_frames")
func aimer_ios_pause_frames() {
    DispatchQueue.main.async {
        FrameDriver.shared.pause()
    }
}

final class KeyboardForwardingTextView: UITextView, UITextViewDelegate {
    override var canBecomeFirstResponder: Bool { true }

    private var sessionId: UInt64 = 0
    private var revision: UInt64 = 0
    private var isApplyingRustSnapshot = false
    private var pendingReplacement: (range: NSRange, text: String)?
    private var mirroredText = ""
    private var lastReportedSelection: NSRange?
    private var lastReportedComposing: NSRange?
    private var selectionReportScheduled = false

    override func didMoveToWindow() {
        super.didMoveToWindow()
        // NOTE: `isHidden = true` disables first-responder interaction and prevents
        // software keyboard callbacks. Keep the view effectively invisible via
        // `alpha`/size instead.
        delegate = self
        isHidden = false
        isScrollEnabled = false
        autocorrectionType = .no
        spellCheckingType = .no
        smartQuotesType = .no
        smartDashesType = .no
        smartInsertDeleteType = .no
        keyboardDismissMode = .none
    }

    func applyRustSnapshot(
        sessionId: UInt64,
        revision: UInt64,
        text snapshot: String,
        selectionStart: Int,
        selectionEnd: Int,
        composingStart: Int,
        composingEnd: Int,
        secure: Bool,
        inputKind: Int32
    ) {
        if self.sessionId == sessionId && revision < self.revision {
            return
        }
        if self.sessionId != 0 && sessionId < self.sessionId {
            return
        }

        let newSession = self.sessionId != sessionId
        self.sessionId = sessionId
        self.revision = revision
        pendingReplacement = nil
        selectionReportScheduled = false

        isApplyingRustSnapshot = true
        defer { isApplyingRustSnapshot = false }

        let keyboardType: UIKeyboardType = inputKind == 1 ? .numberPad : .default
        let traitsChanged = isSecureTextEntry != secure || self.keyboardType != keyboardType
        isSecureTextEntry = secure
        self.keyboardType = keyboardType

        if newSession {
            unmarkText()
        }
        if (text ?? "") != snapshot {
            text = snapshot
        }
        let selection = clampedRange(
            start: selectionStart,
            end: selectionEnd,
            utf16Length: snapshot.utf16.count
        )
        if selectedRange != selection {
            selectedRange = selection
        }

        mirroredText = snapshot
        lastReportedSelection = selection
        lastReportedComposing = optionalRange(
            start: composingStart,
            end: composingEnd,
            utf16Length: snapshot.utf16.count
        )
        #if DEBUG
        print("[aimer:kbd] snapshot rev=\(revision) text=\(debugQuote(snapshot)) sel=\(selection) newSession=\(newSession)")
        #endif
        if traitsChanged && isFirstResponder {
            reloadInputViews()
        }
    }

    func textView(
        _ textView: UITextView,
        shouldChangeTextIn range: NSRange,
        replacementText text: String
    ) -> Bool {
        if !isApplyingRustSnapshot {
            pendingReplacement = (range, text)
        }
        return true
    }

    func textViewDidChange(_ textView: UITextView) {
        guard !isApplyingRustSnapshot else { return }
        guard sessionId != 0 else {
            forwardMarkedTextFallback(from: textView)
            return
        }

        // What the keyboard announced in `shouldChangeTextIn` is not always
        // what it performed: CJK keyboards route the actual edit through
        // marked text after announcing something else, and an announced edit
        // may never happen at all. An announced replacement is only trusted
        // when replaying it over the mirrored text reproduces the text the
        // view actually holds; anything else would report an edit the user
        // never made — a stray newline, for one, reads as the Return key on
        // the Rust side and submits the field mid-composition.
        let actual = textView.text ?? ""
        let announced = pendingReplacement
        pendingReplacement = nil
        let replacement: (range: NSRange, text: String)
        if let announced, replayed(announced, on: mirroredText) == actual {
            replacement = announced
        } else if actual != mirroredText {
            #if DEBUG
            if let announced {
                print("[aimer:kbd] dropped announced edit \(debugQuote(announced.text)) at \(announced.range)")
            }
            #endif
            replacement = (
                NSRange(location: 0, length: mirroredText.utf16.count),
                actual
            )
        } else {
            replacement = (NSRange(location: normalizedSelection(in: textView).location, length: 0), "")
        }
        reportDelta(replacing: replacement.range, with: replacement.text, from: textView)
    }

    func textViewDidChangeSelection(_ textView: UITextView) {
        guard !isApplyingRustSnapshot,
              sessionId != 0,
              pendingReplacement == nil,
              !selectionReportScheduled else { return }
        selectionReportScheduled = true
        let scheduledSession = sessionId
        DispatchQueue.main.async { [weak self, weak textView] in
            guard let self, let textView else { return }
            self.selectionReportScheduled = false
            guard !self.isApplyingRustSnapshot,
                  self.sessionId == scheduledSession else { return }
            // An edit announced before this closure ran but never performed
            // would block every later selection report and be misattributed
            // to the next edit; a full runloop turn without the matching
            // `textViewDidChange` marks it as abandoned.
            self.pendingReplacement = nil
            let selection = self.normalizedSelection(in: textView)
            self.reportDelta(
                replacing: NSRange(location: selection.location, length: 0),
                with: "",
                from: textView
            )
        }
    }

    private func reportDelta(replacing range: NSRange, with replacement: String, from textView: UITextView) {
        let selection = normalizedSelection(in: textView)
        let composing = markedRange(in: textView)
        if range.length == 0,
           replacement.isEmpty,
           lastReportedSelection == selection,
           lastReportedComposing == composing {
            return
        }

        let replacementRange = clampedRange(range, utf16Length: mirroredText.utf16.count)
        #if DEBUG
        let markedLabel = composing.map { "\($0)" } ?? "none"
        print("[aimer:kbd] delta rev=\(revision) replace=\(replacementRange) text=\(debugQuote(replacement)) sel=\(selection) marked=\(markedLabel)")
        #endif
        let composingStart = composing?.location ?? -1
        let composingEnd = composing.map { $0.location + $0.length } ?? -1
        let utf8 = replacement.utf8
        if utf8.isEmpty {
            trigger_rust_text_editing_delta(
                sessionId, revision,
                replacementRange.location, replacementRange.location + replacementRange.length,
                nil, 0,
                selection.location, selection.location + selection.length,
                composingStart, composingEnd
            )
        } else {
            let usedContiguousStorage = utf8.withContiguousStorageIfAvailable { buffer -> Bool in
                trigger_rust_text_editing_delta(
                    sessionId, revision,
                    replacementRange.location, replacementRange.location + replacementRange.length,
                    buffer.baseAddress, buffer.count,
                    selection.location, selection.location + selection.length,
                    composingStart, composingEnd
                )
                return true
            } ?? false
            if !usedContiguousStorage {
                let bytes = Array(utf8)
                bytes.withUnsafeBufferPointer { buffer in
                    trigger_rust_text_editing_delta(
                        sessionId, revision,
                        replacementRange.location, replacementRange.location + replacementRange.length,
                        buffer.baseAddress, buffer.count,
                        selection.location, selection.location + selection.length,
                        composingStart, composingEnd
                    )
                }
            }
        }

        mirroredText = textView.text ?? ""
        lastReportedSelection = selection
        lastReportedComposing = composing
    }

    /// Replays `replacement` against `text`, or returns `nil` when its range
    /// does not lie inside it.
    private func replayed(_ replacement: (range: NSRange, text: String), on text: String) -> String? {
        guard replacement.range.location != NSNotFound,
              replacement.range.location + replacement.range.length <= text.utf16.count else {
            return nil
        }
        return (text as NSString).replacingCharacters(in: replacement.range, with: replacement.text)
    }

    #if DEBUG
    /// Quotes `text` for one line of keyboard tracing.
    private func debugQuote(_ text: String) -> String {
        "\"" + text
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r") + "\""
    }
    #endif

    private func normalizedSelection(in textView: UITextView) -> NSRange {
        clampedRange(textView.selectedRange, utf16Length: (textView.text ?? "").utf16.count)
    }

    private func markedRange(in textView: UITextView) -> NSRange? {
        guard let marked = textView.markedTextRange else { return nil }
        let start = textView.offset(from: textView.beginningOfDocument, to: marked.start)
        let end = textView.offset(from: textView.beginningOfDocument, to: marked.end)
        guard start >= 0, end >= 0 else { return nil }
        return clampedRange(
            start: start,
            end: end,
            utf16Length: (textView.text ?? "").utf16.count
        )
    }

    private func clampedRange(_ range: NSRange, utf16Length: Int) -> NSRange {
        guard range.location != NSNotFound else {
            return NSRange(location: utf16Length, length: 0)
        }
        let location = min(range.location, utf16Length)
        return NSRange(location: location, length: min(range.length, utf16Length - location))
    }

    private func clampedRange(start: Int, end: Int, utf16Length: Int) -> NSRange {
        let lower = min(max(min(start, end), 0), utf16Length)
        let upper = min(max(max(start, end), lower), utf16Length)
        return NSRange(location: lower, length: upper - lower)
    }

    private func optionalRange(start: Int, end: Int, utf16Length: Int) -> NSRange? {
        guard start >= 0, end >= 0 else { return nil }
        return clampedRange(start: start, end: end, utf16Length: utf16Length)
    }

    private var forwardedMarkedText = ""
    private let emptyMarker = UnsafePointer<UInt8>(bitPattern: 1)!

    private func forwardMarkedTextFallback(from textView: UITextView) {
        let marked = markedRange(in: textView)
        let value = marked.map { (textView.text as NSString?)?.substring(with: $0) ?? "" } ?? ""
        guard value != forwardedMarkedText else { return }
        forwardedMarkedText = value
        let data = value.data(using: .utf8) ?? Data()
        data.withUnsafeBytes { rawBuffer in
            let base = rawBuffer.bindMemory(to: UInt8.self).baseAddress
            trigger_rust_set_marked_text(base ?? emptyMarker, rawBuffer.count)
        }
    }
}

private struct RustTextState {
    let sessionId: UInt64
    let revision: UInt64
    let text: String
    let selectionStart: Int
    let selectionEnd: Int
    let composingStart: Int
    let composingEnd: Int
    let secure: Bool
    let inputKind: Int32
}

final class KeyboardForwarder {
    static let shared = KeyboardForwarder()
    private(set) var inputView: KeyboardForwardingTextView?
    private var installAttempts: Int = 0
    private var installScheduled: Bool = false
    private var observers: [NSObjectProtocol] = []
    private var pendingTextState: RustTextState?

    private var cachedInputLanguage = ""

    /// The `primaryLanguage` of the keyboard currently attached to the hidden
    /// input view, or an empty string when no keyboard is up.
    ///
    /// UIKit answers `textInputMode` only on the main thread, which is where
    /// every Rust event — and therefore every read of this value — runs; the
    /// cache exists so a read arriving from anywhere else still gets the tag
    /// last observed through `UITextInputMode.currentInputModeDidChangeNotification`.
    var inputLanguageTag: String {
        if Thread.isMainThread {
            refreshInputLanguage()
        }
        return cachedInputLanguage
    }

    fileprivate func refreshInputLanguage() {
        cachedInputLanguage = inputView?.textInputMode?.primaryLanguage ?? ""
    }

    func dismissKeyboard() {
        guard let v = inputView else { return }
        v.resignFirstResponder()
    }

    func showKeyboard() {
        ensureFirstResponder()
    }

    func syncTextState(
        sessionId: UInt64,
        revision: UInt64,
        text: String,
        selectionStart: Int,
        selectionEnd: Int,
        composingStart: Int,
        composingEnd: Int,
        secure: Bool,
        inputKind: Int32
    ) {
        let state = RustTextState(
            sessionId: sessionId,
            revision: revision,
            text: text,
            selectionStart: selectionStart,
            selectionEnd: selectionEnd,
            composingStart: composingStart,
            composingEnd: composingEnd,
            secure: secure,
            inputKind: inputKind
        )
        if let pendingTextState {
            if pendingTextState.sessionId == sessionId && revision < pendingTextState.revision {
                return
            }
            if sessionId < pendingTextState.sessionId {
                return
            }
        }
        pendingTextState = state
        if inputView == nil {
            installIfPossible()
        }
        applyPendingTextState()
    }

    private func ensureFirstResponder() {
        if inputView == nil {
            installIfPossible()
            return
        }
        guard let v = inputView else { return }
        _ = v.becomeFirstResponder()
    }

    private func applyPendingTextState() {
        guard let view = inputView, let state = pendingTextState else { return }
        pendingTextState = nil
        view.applyRustSnapshot(
            sessionId: state.sessionId,
            revision: state.revision,
            text: state.text,
            selectionStart: state.selectionStart,
            selectionEnd: state.selectionEnd,
            composingStart: state.composingStart,
            composingEnd: state.composingEnd,
            secure: state.secure,
            inputKind: state.inputKind
        )
    }

    private func keyWindow() -> UIWindow? {
        if #available(iOS 13.0, *) {
            let scenes = UIApplication.shared.connectedScenes
                .compactMap { $0 as? UIWindowScene }

            // Prefer a foreground-active scene.
            let orderedScenes = scenes.sorted { lhs, rhs in
                let lhsActive = lhs.activationState == .foregroundActive
                let rhsActive = rhs.activationState == .foregroundActive
                return lhsActive && !rhsActive
            }

            for scene in orderedScenes {
                if let win = scene.windows.first(where: { $0.isKeyWindow }) {
                    return win
                }
            }
        }

        // Fallback for older iOS / edge cases.
        return UIApplication.shared.windows.first(where: { $0.isKeyWindow })
    }

    private func scheduleRetry() {
        guard !installScheduled else { return }
        installScheduled = true

        // Retry a few times to wait for winit to create its UIWindow.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.10) { [weak self] in
            guard let self else { return }
            self.installScheduled = false
            self.installIfPossible()
        }
    }

    func installIfPossible() {
        guard inputView == nil else { return }

        guard let window = keyWindow() else {
            installAttempts += 1
            if installAttempts < 50 {
                scheduleRetry()
            }
            return
        }

        let v = KeyboardForwardingTextView(frame: CGRect(x: 0, y: 0, width: 1, height: 1))
        v.alpha = 0.01
        window.addSubview(v)
        window.bringSubviewToFront(v)
        inputView = v
        applyPendingTextState()
    }

    func start() {
        // Important: winit calls `UIApplicationMain` internally.
        // Depending on iOS / scene lifecycle, a custom `UIApplicationDelegate` may not be
        // reliably used. So we install from notifications + retry loop instead of relying on
        // delegate callbacks.
        if observers.isEmpty {
            let center = NotificationCenter.default

            observers.append(center.addObserver(
                forName: UIApplication.didBecomeActiveNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in
                self?.installIfPossible()
            })

            observers.append(center.addObserver(
                forName: UIApplication.willEnterForegroundNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in
                self?.installIfPossible()
            })

            // When the software keyboard is shown, UIKit/winit may change first responder.
            // Re-assert first responder so `insertText`/`deleteBackward` keep coming to our view.
            observers.append(center.addObserver(
                forName: UIResponder.keyboardWillShowNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in
                self?.ensureFirstResponder()
            })

            observers.append(center.addObserver(
                forName: UIResponder.keyboardDidShowNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in

                self?.ensureFirstResponder()
            })

            observers.append(center.addObserver(
                forName: UIWindow.didBecomeKeyNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in
                self?.ensureFirstResponder()
            })

            // Switching keyboards mid-editing changes the language the next
            // characters are written in; refreshing the cache here keeps the
            // tag Rust reads on the following keystroke current.
            observers.append(center.addObserver(
                forName: UITextInputMode.currentInputModeDidChangeNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in
                self?.refreshInputLanguage()
            })
        }

        // Also try immediately (this will schedule retries until a key window exists).
        installIfPossible()
    }
}

KeyboardForwarder.shared.start()
FrameDriver.shared.start()

#if DEBUG
print("Starting AimerApplication...")
#endif
__generated_entrance_point()