[application]
name = "website"
version = "0.0.1"
group = "com.example.jaime"


[assets]
# Files bundled into every platform package. The path below is used verbatim
# as the runtime lookup key, e.g. `AssetImage!("image.png")`.
files = [
    "assets/polished_tooling.png",
    "assets/web_screenshot.png",
    "assets/ios_screenshot.png",
    "assets/macos_screenshot.png",
    "assets/android_screenshot.png",
    "assets/github-svgrepo-com.png",
    "assets/back-svgrepo-com.svg"
]
