[package]
name = "website"
version = "0.1.0"
edition = "2024"

[features]
default = ["native", "desktop-bin"]
native = ["aimer/markdown", "aimer/svg", "aimer/provider"]

desktop-bin = []


[lib]
path = "src/main.rs"
crate-type = ["cdylib", "staticlib", "rlib"]

[[bin]]
name = "website"
path = "src/main.rs"
required-features = ["desktop-bin"]

[dependencies]
aimer = { path = ".." }
webbrowser = "1.2.1"
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
muda = "0.19.3"

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread"] }
aimer_cli = { path = "../aimer_cli" }
tempfile.workspace = true
