[package]
name = "website"
version = "0.1.0"
edition = "2024"

[features]
desktop-bin = []


[lib]
path = "src/main.rs"
crate-type = ["cdylib", "staticlib", "rlib"]

[[bin]]
name = "website"
path = "src/main.rs"

[dependencies]
aimer = { path = "..", features = ["provider", "markdown", "markdown-arborium", "svg"]}
webbrowser = "1.2.1"
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
muda = "0.19.3"

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread"] }