//! Bakes the blog markdown in `content/blogs` into the compiled artifact.
//!
//! A Cloudflare Worker runs as a WebAssembly module with no filesystem, so the
//! documents the API serves cannot be read at runtime. This script turns every
//! `content/blogs/*.md` file into an entry of a `&'static str` table which
//! [`website_backend::content`] includes, keyed by the file stem — the blog id.
//!
//! The table lists every markdown file, not only the published ones: whether a
//! document is served is decided by `content/blogs/index.json` at load time, so
//! a draft can sit next to the published posts without being reachable.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("cargo always sets the manifest dir");
    let content = Path::new(&manifest).join("content/blogs");
    println!("cargo::rerun-if-changed={}", content.display());

    let mut documents = markdown_documents(&content);
    documents.sort_by(|left, right| left.0.cmp(&right.0));

    let mut generated = String::with_capacity(documents.len() * 128);
    generated.push_str(
        "/// Every markdown document in `content/blogs`, keyed by its blog id.\n\
         ///\n\
         /// Generated by `build.rs`; sorted by id so the table is reproducible.\n\
         pub(crate) static EMBEDDED_MARKDOWN: &[(&str, &str)] = &[\n",
    );
    for (id, path) in &documents {
        println!("cargo::rerun-if-changed={}", path.display());
        let path = path.display().to_string();
        writeln!(generated, "    ({id:?}, include_str!({path:?})),")
            .expect("writing to a string never fails");
    }
    generated.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("cargo always sets the output dir");
    let destination = Path::new(&out_dir).join("embedded_markdown.rs");
    std::fs::write(&destination, generated)
        .unwrap_or_else(|error| panic!("writing {}: {error}", destination.display()));
}

/// Collects the id and path of every markdown document in `content`.
fn markdown_documents(content: &Path) -> Vec<(String, PathBuf)> {
    std::fs::read_dir(content)
        .unwrap_or_else(|error| panic!("reading {}: {error}", content.display()))
        .map(|entry| {
            entry
                .unwrap_or_else(|error| panic!("reading {}: {error}", content.display()))
                .path()
        })
        .filter(|path| path.extension().is_some_and(|extension| extension == "md"))
        .map(|path| {
            let id = path
                .file_stem()
                .expect("a markdown file always has a stem")
                .to_str()
                .unwrap_or_else(|| panic!("{} is not valid UTF-8", path.display()))
                .to_owned();

            (id, path)
        })
        .collect()
}
