[package]
name = "website_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
worker = { version = "0.8", features = ['http', 'axum'] }
worker-macros = { version = "0.8", features = ['http'] }
axum = { workspace = true, features = ["http1", "json", "tokio"] }
dotenvy.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "net", "rt-multi-thread"] }
tower-http = { version = "0.7.0", features = ["cors"] }


[dev-dependencies]
aimer_rubick.workspace = true
tempfile.workspace = true
tower.workspace = true
