use std::collections::HashMap;

use aimer_widget::Widget;
use aimer_widget::base::BuildContext;

/// The result of matching a URL against a [`Route`].
///
/// Holds the parameters extracted from the path (e.g. `{id}` in `/user/{id}`)
/// and the query string (e.g. `?q=foo&page=2`).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RouteMatch {
    pub path_params: HashMap<String, String>,
    pub query_params: HashMap<String, String>,
}

impl RouteMatch {
    pub fn new() -> Self {
        Self::default()
    }

    /// Fetch a path parameter by name.
    pub fn path_param(&self, key: &str) -> Option<&str> {
        self.path_params
            .get(key)
            .map(String::as_str)
    }

    /// Fetch a query parameter by name.
    pub fn query_param(&self, key: &str) -> Option<&str> {
        self.query_params
            .get(key)
            .map(String::as_str)
    }
}

pub trait Route: Clone + Send + Sync + 'static {
    fn parse(path: &str) -> Option<Self>
    where
        Self: Sized;
    fn format(&self) -> String;

    /// A stable, developer-facing name for this route (e.g. `"user"`), used by
    /// `NavigatorController::push_named`. Defaults to `None` for routes that do
    /// not opt into named navigation.
    fn name(&self) -> Option<&'static str> {
        None
    }

    /// Guard/redirect hook. Return `Some(other_route)` to transparently reroute
    /// before this route's widget is built (e.g. sending an unauthenticated
    /// user to `/login`); return `None` to proceed with `self`.
    ///
    /// Routes generated by `#[widget(Router)]` with a `#[redirect(...)]`
    /// attribute override this. The default performs no redirect.
    fn redirect(&self, _ctx: &BuildContext) -> Option<Self>
    where
        Self: Sized,
    {
        None
    }

    /// Resolve a route by its declared name and a set of path/query parameters.
    ///
    /// Routes generated by `#[widget(Router)]` with a `name = "..."` attribute
    /// override this to look the name up in the generated table. The default
    /// returns `None` (no named routes).
    fn resolve_named(_name: &str, _params: &HashMap<String, String>) -> Option<Self>
    where
        Self: Sized,
    {
        None
    }
}

/// Split a full path into its path portion and a parsed query-parameter map.
///
/// `"/search?q=foo&page=2"` -> `("/search", {"q": "foo", "page": "2"})`.
pub fn split_path_query(full: &str) -> (&str, HashMap<String, String>) {
    match full.split_once('?') {
        Some((path, query)) => (path, parse_query_string(query)),
        None => (full, HashMap::new()),
    }
}

/// Parse a query string (without the leading `?`) into a key/value map.
pub fn parse_query_string(query: &str) -> HashMap<String, String> {
    let mut map = HashMap::new();
    for pair in query.split('&') {
        if pair.is_empty() {
            continue;
        }
        match pair.split_once('=') {
            Some((k, v)) => {
                map.insert(k.to_string(), v.to_string());
            }
            None => {
                map.insert(pair.to_string(), String::new());
            }
        }
    }
    map
}

/// Format a key/value map into a query string, sorted for deterministic output.
///
/// Returns an empty string when there are no parameters (so callers can append
/// it unconditionally).
pub fn format_query_string(params: &[(String, String)]) -> String {
    if params.is_empty() {
        return String::new();
    }
    let mut parts: Vec<String> = params
        .iter()
        .map(|(k, v)| format!("{k}={v}"))
        .collect();
    parts.sort();
    format!("?{}", parts.join("&"))
}

pub trait Router {
    fn build(&self, ctx: &BuildContext) -> Box<dyn Widget>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn split_path_query_without_query() {
        let (path, query) = split_path_query("/search");
        assert_eq!(path, "/search");
        assert!(query.is_empty());
    }

    #[test]
    fn split_path_query_with_query() {
        let (path, query) = split_path_query("/search?q=foo&page=2");
        assert_eq!(path, "/search");
        assert_eq!(query.get("q"), Some(&"foo".to_string()));
        assert_eq!(query.get("page"), Some(&"2".to_string()));
    }

    #[test]
    fn parse_query_handles_flag_and_empty() {
        let q = parse_query_string("flag&q=");
        assert_eq!(q.get("flag"), Some(&String::new()));
        assert_eq!(q.get("q"), Some(&String::new()));
    }

    #[test]
    fn format_query_is_sorted_and_prefixed() {
        let params =
            vec![("page".to_string(), "2".to_string()), ("q".to_string(), "foo".to_string())];
        assert_eq!(format_query_string(&params), "?page=2&q=foo");
    }

    #[test]
    fn format_query_empty_is_blank() {
        assert_eq!(format_query_string(&[]), "");
    }

    #[test]
    fn route_match_accessors() {
        let mut m = RouteMatch::new();
        m.path_params
            .insert("id".to_string(), "42".to_string());
        m.query_params
            .insert("q".to_string(), "foo".to_string());
        assert_eq!(m.path_param("id"), Some("42"));
        assert_eq!(m.query_param("q"), Some("foo"));
        assert_eq!(m.path_param("missing"), None);
    }
}
